CREATE DATABASE DB_MARKET;
GO;
USE DB_MARKET;

CREATE TABLE TBL_USER(
USER_ID INT PRIMARY KEY IDENTITY,
FULL_NAME NVARCHAR(255),
USER_NAME NVARCHAR(255) NOT NULL,
PASS NVARCHAR(255) NOT NULL,
ROLEE NVARCHAR(255) NOT NULL,
SALARY  DECIMAL(10, 3),
IMAGE_PATH Varbinary(MAX) ,
--DATE_OF_START DATETIME DEFAULT GETDATE()
  DATE_OF_START DATE DEFAULT CAST(GETDATE() AS DATE)
--DATE_OF_START DATETIME2(0) DEFAULT FORMAT(GETDATE(), 'yyyy-MM-dd HH:mm')
);
DROP TABLE TBL_USER
DELETE  FROM TBL_USER;
SELECT * FROM TBL_USER;

INSERT INTO TBL_USER(FULL_NAME,USER_NAME,PASS,ROLEE,SALARY)VALUES
('','','',N'بــەڕێــوبــەر',20);


INSERT INTO TBL_USER(FULL_NAME,USER_NAME,PASS,ROLEE,SALARY)VALUES
('','',N'سش١٢٣',N'کــارمــەنــد',10);


INSERT INTO TBL_USER(FULL_NAME,USER_NAME,PASS,ROLEE,SALARY)VALUES
(N'بــلال مـو‌‌‌حــەمــەد','b','b',N'کــارمــەنــد',10);

INSERT INTO TBL_USER (FULL_NAME, USER_NAME, PASS, ROLEE, SALARY, IMAGE_PATH)
VALUES 
('John Doe', 'j', '3', N'کــارمــەنــد', 5000, 'C:\\Users\\Fedyas Muhammad\\Desktop\\DB_Market\\IMAGE\\TALABAT.png');



INSERT INTO TBL_USER (FULL_NAME, USER_NAME, PASS, ROLEE, SALARY, IMAGE_PATH)
VALUES 
('bill', 'b', '4', N'کــارمــەنــد', 5000, 'C:\\Users\\Fedyas Muhammad\\Desktop\\DB_Market\\IMAGE\\s.jfif');


